package reachability;
import java.util.*;
import java.io.*;

class semaphoreIDGenerator {
	private HashMap names = new HashMap();


	private static final Object classLock = semaphoreIDGenerator.class;

	private static semaphoreIDGenerator instance = null;

	private PrintWriter outputThreadID = null;

	private semaphoreIDGenerator() {
		try {
	   	outputThreadID = new PrintWriter(new FileOutputStream("semaphoreID.txt"));
		}
      catch (IOException e) {
       System.err.println("File not opened: " + e.toString());
        System.exit(1);
     }
	}


	public static semaphoreIDGenerator getInstance() { 
		synchronized(classLock) {
      	if (instance == null)
        		instance = new semaphoreIDGenerator();
		}
      return instance;
    }


	private synchronized boolean containsName(String stringID) {
		return names.containsKey(stringID);
	}

	private synchronized void putName(String name, Integer num) {
	// associates name with num
		names.put(name, num);
	   outputThreadID.println(name+num);
		outputThreadID.flush();
	}

	private synchronized void putUserName(String name, Integer num) {
	// associates name with num, but IDs are not used for semaphores for tracing/replay/test
	// For RT, IDs are generated by call to ThreadIDGenerator so that semaphores have a 
	// position in the vector timestamps
		names.put(name, num);
		// num is always 1
	   outputThreadID.println(name);
		outputThreadID.flush();
	}

	private synchronized int getNum(String name) {
	// gets num associated with name
		return ((Integer)names.get(name)).intValue();
	}

		public synchronized String getID(String stringID) {
		// returns name generated for semaphore; integer IDs are not generated/used
			String nextName=null;
			// check to see if this is first instance of this semaphore class
			// id has two tables:
			//	1. instance table of (className, #instances)
			if (!containsName(stringID)){
				// first semaphore
				nextName = stringID + "1"; // next className+instance# for identifier table
				putName(stringID, new Integer(1)); // add to instance table
			}
			else {
				// at least one instance already exists
				int nextNum = getNum(stringID)+1;
				nextName = stringID + nextNum; // next className+instance# for identifier table
				putName(stringID,new Integer(nextNum)); // add to instance table
			}
			return nextName;
		}

		public synchronized String getIDFromUserName(String userName) {
		// returns name generated for semaphore; integer IDs are not generated/used
		// name is the name given by the user
			if (!containsName(userName)){
					// first thread of this class
					putUserName(userName, new Integer(1)); // add to instance table
				}
			else {
				// at least one instance already exists
				throw new InvalidSemaphoreName("Use of duplicate semaphore name: " + "\""+userName+"\"");
			}
     	 return userName;
		}

  }

final class InvalidSemaphoreName extends InvalidIDException {
	InvalidSemaphoreName() { }
	InvalidSemaphoreName(String msg) {super(msg);}
}
